apiVersion: v1 
kind: PersistentVolume
metadata:
  name: mongo
spec:
  storageClassName: nodestorage
  capacity:
    storage: 10Gi #we are consuming 10gi of storage. but this is thin provisioning. 
  accessModes: 
      - ReadWriteOnce #readwritemany #read
  hostPath:
      path: /mnt/data